services:
  - type: web
    name: pesquisa-transporte
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT srcmain:"
    healthCheckPath: "/health"
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: pesquisa-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production

databases:
  - name: pesquisa-db
    databaseName: pesquisa_transporte
    user: pesquisa_user
    plan: free
